# Generated by Django 2.2 on 2019-05-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='subtitle',
            field=models.CharField(default='12', max_length=100, verbose_name='Subtitulo Motivador'),
        ),
    ]
