# Generated by Django 2.2 on 2019-06-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiaDestinos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Titulo')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, null=True, upload_to='noticias', verbose_name='Imagen')),
                ('btn', models.CharField(max_length=140, verbose_name='Texto del boton')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateField(auto_now_add=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Noticia Destinos',
                'verbose_name_plural': 'noticia',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='NoticiaHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140, verbose_name='Titulo')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('image', models.ImageField(blank=True, null=True, upload_to='noticias', verbose_name='Imagen')),
                ('btn', models.CharField(max_length=140, verbose_name='Texto del boton')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateField(auto_now_add=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Noticia Home',
                'verbose_name_plural': 'noticia',
                'ordering': ['-created'],
            },
        ),
    ]
