# Generated by Django 2.2 on 2019-06-29 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticiadestinos',
            options={'ordering': ['-created'], 'verbose_name': 'Noticia Destinos', 'verbose_name_plural': 'Noticia Pagina Destinos'},
        ),
        migrations.AlterModelOptions(
            name='noticiahome',
            options={'ordering': ['-created'], 'verbose_name': 'Noticia Home', 'verbose_name_plural': 'Noticia Pagina Home'},
        ),
    ]
