# Generated by Django 2.2 on 2019-05-19 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del cliente')),
                ('content', models.TextField(verbose_name='Comentario')),
                ('starts', models.IntegerField(max_length=6, verbose_name='Estrellas')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateField(auto_now_add=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'testimonio',
                'verbose_name_plural': 'Crear Testimonio',
                'ordering': ['-created'],
            },
        ),
    ]
