# Generated by Django 2.2 on 2019-05-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_testimonios'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerPrincipalBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titulo')),
                ('content', models.TextField(verbose_name='Contenido')),
                ('NameBtn', models.CharField(default='Haz click aquí', max_length=30, verbose_name='Nombre del boton')),
                ('url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace')),
                ('created', models.DateField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateField(auto_now_add=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'banner',
                'verbose_name_plural': 'Cambiar Texto Banner Blog',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='testimonios',
            name='starts',
            field=models.IntegerField(verbose_name='Estrellas'),
        ),
    ]
