# Generated by Django 2.2 on 2019-06-18 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alumno'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
