# Generated by Django 2.2 on 2019-06-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0002_auto_20190628_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='paquetes', verbose_name='Imagen'),
        ),
    ]
