# Generated by Django 2.2 on 2019-07-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_auto_20190628_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del pais')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='paquete',
            name='pais',
            field=models.ManyToManyField(related_name='get_pais', to='viajes.Pais', verbose_name='Pais'),
        ),
    ]
