# Generated by Django 2.2 on 2019-07-06 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0005_auto_20190704_2052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='galeria', verbose_name='Imagen')),
                ('paquete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='viajes.Paquete', verbose_name='Imagenes que incluye')),
            ],
        ),
    ]
