# Generated by Django 2.2 on 2019-07-07 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0007_subincluye_subnoincluye'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subnoincluye',
            name='noincluye',
        ),
        migrations.DeleteModel(
            name='SubIncluye',
        ),
        migrations.DeleteModel(
            name='SubNoIncluye',
        ),
    ]
