# Generated by Django 2.2 on 2019-07-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0009_auto_20190706_2326'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='mostrarPrimero',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paquete',
            name='oferta',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paquete',
            name='porcentajeoferta',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='1 a 100'),
            preserve_default=False,
        ),
    ]
