# Generated by Django 2.2 on 2019-07-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0014_auto_20190707_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='mostrarPrimero',
        ),
        migrations.AlterField(
            model_name='plan',
            name='doble',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio doble'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='extradoble',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio Noche extra doble'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='extraniños',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio noche extra niños'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='extrasencilla',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio Noche extra sencilla'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='extratriple',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio Noche extra triple'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='niños',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio niños'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='sencilla',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio sencilla'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='triple',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio triple'),
        ),
    ]
