# Generated by Django 2.2 on 2019-07-07 23:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0015_auto_20190707_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='categoriaHotel',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='doble',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='extradoble',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='extraniños',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='extrasencilla',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='extratriple',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='hotel',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='niños',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='sencilla',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='triple',
        ),
        migrations.CreateModel(
            name='Planes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.CharField(max_length=100, verbose_name='Hotel')),
                ('categoriaHotel', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='1 a 5')),
                ('sencilla', models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio sencilla')),
                ('extrasencilla', models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio Noche extra sencilla')),
                ('doble', models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio doble')),
                ('extradoble', models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio Noche extra doble')),
                ('triple', models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio triple')),
                ('extratriple', models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio Noche extra triple')),
                ('niños', models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio niños')),
                ('extraniños', models.PositiveIntegerField(blank=True, null=True, verbose_name='Precio noche extra niños')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_plans', to='viajes.Plan')),
            ],
        ),
    ]
