# Generated by Django 2.2 on 2019-06-28 23:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0003_auto_20190628_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paquete',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='paquete',
            name='created',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2019, 6, 28, 23, 26, 57, 36579, tzinfo=utc), verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paquete',
            name='updated',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2019, 6, 28, 23, 27, 5, 638592, tzinfo=utc), verbose_name='Fecha de edición'),
            preserve_default=False,
        ),
    ]
