# Generated by Django 2.2 on 2019-06-29 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_auto_20190629_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiahome',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Enlace'),
        ),
    ]
